// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.2
// source: ner-apk-proto/ishlab_chiqarish/shartnoma.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewInsideTheContractGetAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractGetAllReq) Reset() {
	*x = NewInsideTheContractGetAllReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractGetAllReq) ProtoMessage() {}

func (x *NewInsideTheContractGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractGetAllReq.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractGetAllReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{0}
}

func (x *NewInsideTheContractGetAllReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NewInsideTheContractGetAllReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type NewInsideTheContractGetAllRes struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	All           []*NewInsideTheContractt `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractGetAllRes) Reset() {
	*x = NewInsideTheContractGetAllRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractGetAllRes) ProtoMessage() {}

func (x *NewInsideTheContractGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractGetAllRes.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractGetAllRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{1}
}

func (x *NewInsideTheContractGetAllRes) GetAll() []*NewInsideTheContractt {
	if x != nil {
		return x.All
	}
	return nil
}

type NewInsideTheContractt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractId    string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Situation     string                 `protobuf:"bytes,5,opt,name=situation,proto3" json:"situation,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractt) Reset() {
	*x = NewInsideTheContractt{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractt) ProtoMessage() {}

func (x *NewInsideTheContractt) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractt.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractt) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{2}
}

func (x *NewInsideTheContractt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewInsideTheContractt) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NewInsideTheContractt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewInsideTheContractt) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *NewInsideTheContractt) GetSituation() string {
	if x != nil {
		return x.Situation
	}
	return ""
}

func (x *NewInsideTheContractt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NewInsideTheContractt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NewInsideTheContractDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractDeleteReq) Reset() {
	*x = NewInsideTheContractDeleteReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractDeleteReq) ProtoMessage() {}

func (x *NewInsideTheContractDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractDeleteReq.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractDeleteReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{3}
}

func (x *NewInsideTheContractDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewInsideTheContractDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractDeleteRes) Reset() {
	*x = NewInsideTheContractDeleteRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractDeleteRes) ProtoMessage() {}

func (x *NewInsideTheContractDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractDeleteRes.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractDeleteRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{4}
}

func (x *NewInsideTheContractDeleteRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewInsideTheContractUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Situation     string                 `protobuf:"bytes,5,opt,name=situation,proto3" json:"situation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractUpdateReq) Reset() {
	*x = NewInsideTheContractUpdateReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractUpdateReq) ProtoMessage() {}

func (x *NewInsideTheContractUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractUpdateReq.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractUpdateReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{5}
}

func (x *NewInsideTheContractUpdateReq) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NewInsideTheContractUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewInsideTheContractUpdateReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *NewInsideTheContractUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewInsideTheContractUpdateReq) GetSituation() string {
	if x != nil {
		return x.Situation
	}
	return ""
}

type NewInsideTheContractUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractUpdateRes) Reset() {
	*x = NewInsideTheContractUpdateRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractUpdateRes) ProtoMessage() {}

func (x *NewInsideTheContractUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractUpdateRes.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractUpdateRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{6}
}

func (x *NewInsideTheContractUpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewInsideTheContractReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractReq) Reset() {
	*x = NewInsideTheContractReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractReq) ProtoMessage() {}

func (x *NewInsideTheContractReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractReq.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{7}
}

func (x *NewInsideTheContractReq) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NewInsideTheContractReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewInsideTheContractReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type NewInsideTheContractRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewInsideTheContractRes) Reset() {
	*x = NewInsideTheContractRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewInsideTheContractRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsideTheContractRes) ProtoMessage() {}

func (x *NewInsideTheContractRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsideTheContractRes.ProtoReflect.Descriptor instead.
func (*NewInsideTheContractRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{8}
}

func (x *NewInsideTheContractRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewContractGetAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractGetAllReq) Reset() {
	*x = NewContractGetAllReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractGetAllReq) ProtoMessage() {}

func (x *NewContractGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractGetAllReq.ProtoReflect.Descriptor instead.
func (*NewContractGetAllReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{9}
}

func (x *NewContractGetAllReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NewContractGetAllReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type NewContractGetAllRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      []*Contract            `protobuf:"bytes,1,rep,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractGetAllRes) Reset() {
	*x = NewContractGetAllRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractGetAllRes) ProtoMessage() {}

func (x *NewContractGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractGetAllRes.ProtoReflect.Descriptor instead.
func (*NewContractGetAllRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{10}
}

func (x *NewContractGetAllRes) GetContract() []*Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type NewContractGetNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractGetNameReq) Reset() {
	*x = NewContractGetNameReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractGetNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractGetNameReq) ProtoMessage() {}

func (x *NewContractGetNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractGetNameReq.ProtoReflect.Descriptor instead.
func (*NewContractGetNameReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{11}
}

func (x *NewContractGetNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewContractGetNameRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractName      string                 `protobuf:"bytes,2,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractNumber    string                 `protobuf:"bytes,3,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	ContractDeadline  string                 `protobuf:"bytes,4,opt,name=contract_deadline,json=contractDeadline,proto3" json:"contract_deadline,omitempty"`
	ContractFileUrl   string                 `protobuf:"bytes,5,opt,name=contract_file_url,json=contractFileUrl,proto3" json:"contract_file_url,omitempty"`
	ResponsiblePerson string                 `protobuf:"bytes,6,opt,name=responsible_person,json=responsiblePerson,proto3" json:"responsible_person,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NewContractGetNameRes) Reset() {
	*x = NewContractGetNameRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractGetNameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractGetNameRes) ProtoMessage() {}

func (x *NewContractGetNameRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractGetNameRes.ProtoReflect.Descriptor instead.
func (*NewContractGetNameRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{12}
}

func (x *NewContractGetNameRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewContractGetNameRes) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *NewContractGetNameRes) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *NewContractGetNameRes) GetContractDeadline() string {
	if x != nil {
		return x.ContractDeadline
	}
	return ""
}

func (x *NewContractGetNameRes) GetContractFileUrl() string {
	if x != nil {
		return x.ContractFileUrl
	}
	return ""
}

func (x *NewContractGetNameRes) GetResponsiblePerson() string {
	if x != nil {
		return x.ResponsiblePerson
	}
	return ""
}

type NewContractDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractDeleteReq) Reset() {
	*x = NewContractDeleteReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractDeleteReq) ProtoMessage() {}

func (x *NewContractDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractDeleteReq.ProtoReflect.Descriptor instead.
func (*NewContractDeleteReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{13}
}

func (x *NewContractDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewContractDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractDeleteRes) Reset() {
	*x = NewContractDeleteRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractDeleteRes) ProtoMessage() {}

func (x *NewContractDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractDeleteRes.ProtoReflect.Descriptor instead.
func (*NewContractDeleteRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{14}
}

func (x *NewContractDeleteRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewContractUpdateReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractName      string                 `protobuf:"bytes,2,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractNumber    string                 `protobuf:"bytes,3,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	ContractDeadline  string                 `protobuf:"bytes,4,opt,name=contract_deadline,json=contractDeadline,proto3" json:"contract_deadline,omitempty"`
	ContractFileUrl   string                 `protobuf:"bytes,5,opt,name=contract_file_url,json=contractFileUrl,proto3" json:"contract_file_url,omitempty"`
	ResponsiblePerson string                 `protobuf:"bytes,6,opt,name=responsible_person,json=responsiblePerson,proto3" json:"responsible_person,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NewContractUpdateReq) Reset() {
	*x = NewContractUpdateReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractUpdateReq) ProtoMessage() {}

func (x *NewContractUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractUpdateReq.ProtoReflect.Descriptor instead.
func (*NewContractUpdateReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{15}
}

func (x *NewContractUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewContractUpdateReq) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *NewContractUpdateReq) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *NewContractUpdateReq) GetContractDeadline() string {
	if x != nil {
		return x.ContractDeadline
	}
	return ""
}

func (x *NewContractUpdateReq) GetContractFileUrl() string {
	if x != nil {
		return x.ContractFileUrl
	}
	return ""
}

func (x *NewContractUpdateReq) GetResponsiblePerson() string {
	if x != nil {
		return x.ResponsiblePerson
	}
	return ""
}

type NewContractUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractUpdateRes) Reset() {
	*x = NewContractUpdateRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractUpdateRes) ProtoMessage() {}

func (x *NewContractUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractUpdateRes.ProtoReflect.Descriptor instead.
func (*NewContractUpdateRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{16}
}

func (x *NewContractUpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewContractReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContractName      string                 `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractNumber    string                 `protobuf:"bytes,2,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	ContractDeadline  string                 `protobuf:"bytes,3,opt,name=contract_deadline,json=contractDeadline,proto3" json:"contract_deadline,omitempty"`
	ContractFileUrl   string                 `protobuf:"bytes,4,opt,name=contract_file_url,json=contractFileUrl,proto3" json:"contract_file_url,omitempty"`
	ResponsiblePerson string                 `protobuf:"bytes,5,opt,name=responsible_person,json=responsiblePerson,proto3" json:"responsible_person,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NewContractReq) Reset() {
	*x = NewContractReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractReq) ProtoMessage() {}

func (x *NewContractReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractReq.ProtoReflect.Descriptor instead.
func (*NewContractReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{17}
}

func (x *NewContractReq) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *NewContractReq) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *NewContractReq) GetContractDeadline() string {
	if x != nil {
		return x.ContractDeadline
	}
	return ""
}

func (x *NewContractReq) GetContractFileUrl() string {
	if x != nil {
		return x.ContractFileUrl
	}
	return ""
}

func (x *NewContractReq) GetResponsiblePerson() string {
	if x != nil {
		return x.ResponsiblePerson
	}
	return ""
}

type NewContractRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContractRes) Reset() {
	*x = NewContractRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContractRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContractRes) ProtoMessage() {}

func (x *NewContractRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContractRes.ProtoReflect.Descriptor instead.
func (*NewContractRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{18}
}

func (x *NewContractRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Contract struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractName      string                 `protobuf:"bytes,2,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractNumber    string                 `protobuf:"bytes,3,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	ContractDeadline  string                 `protobuf:"bytes,4,opt,name=contract_deadline,json=contractDeadline,proto3" json:"contract_deadline,omitempty"`
	ContractFileUrl   string                 `protobuf:"bytes,5,opt,name=contract_file_url,json=contractFileUrl,proto3" json:"contract_file_url,omitempty"`
	ResponsiblePerson string                 `protobuf:"bytes,6,opt,name=responsible_person,json=responsiblePerson,proto3" json:"responsible_person,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP(), []int{19}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *Contract) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *Contract) GetContractDeadline() string {
	if x != nil {
		return x.ContractDeadline
	}
	return ""
}

func (x *Contract) GetContractFileUrl() string {
	if x != nil {
		return x.ContractFileUrl
	}
	return ""
}

func (x *Contract) GetResponsiblePerson() string {
	if x != nil {
		return x.ResponsiblePerson
	}
	return ""
}

func (x *Contract) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Contract) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_ner_apk_proto_ishlab_chiqarish_shartnoma_proto protoreflect.FileDescriptor

const file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDesc = "" +
	"\n" +
	".ner-apk-proto/ishlab_chiqarish/shartnoma.proto\x12\bcontract\"I\n" +
	"\x1dNewInsideTheContractGetAllReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"R\n" +
	"\x1dNewInsideTheContractGetAllRes\x121\n" +
	"\x03all\x18\x01 \x03(\v2\x1f.contract.NewInsideTheContracttR\x03all\"\xce\x01\n" +
	"\x15NewInsideTheContractt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1c\n" +
	"\tsituation\x18\x05 \x01(\tR\tsituation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"/\n" +
	"\x1dNewInsideTheContractDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x1dNewInsideTheContractDeleteRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x98\x01\n" +
	"\x1dNewInsideTheContractUpdateReq\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1c\n" +
	"\tsituation\x18\x05 \x01(\tR\tsituation\"9\n" +
	"\x1dNewInsideTheContractUpdateRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"d\n" +
	"\x17NewInsideTheContractReq\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\"3\n" +
	"\x17NewInsideTheContractRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x14NewContractGetAllReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\"F\n" +
	"\x14NewContractGetAllRes\x12.\n" +
	"\bcontract\x18\x01 \x03(\v2\x12.contract.ContractR\bcontract\"+\n" +
	"\x15NewContractGetNameReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xfd\x01\n" +
	"\x15NewContractGetNameRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcontract_name\x18\x02 \x01(\tR\fcontractName\x12'\n" +
	"\x0fcontract_number\x18\x03 \x01(\tR\x0econtractNumber\x12+\n" +
	"\x11contract_deadline\x18\x04 \x01(\tR\x10contractDeadline\x12*\n" +
	"\x11contract_file_url\x18\x05 \x01(\tR\x0fcontractFileUrl\x12-\n" +
	"\x12responsible_person\x18\x06 \x01(\tR\x11responsiblePerson\"&\n" +
	"\x14NewContractDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14NewContractDeleteRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xfc\x01\n" +
	"\x14NewContractUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcontract_name\x18\x02 \x01(\tR\fcontractName\x12'\n" +
	"\x0fcontract_number\x18\x03 \x01(\tR\x0econtractNumber\x12+\n" +
	"\x11contract_deadline\x18\x04 \x01(\tR\x10contractDeadline\x12*\n" +
	"\x11contract_file_url\x18\x05 \x01(\tR\x0fcontractFileUrl\x12-\n" +
	"\x12responsible_person\x18\x06 \x01(\tR\x11responsiblePerson\"0\n" +
	"\x14NewContractUpdateRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe6\x01\n" +
	"\x0eNewContractReq\x12#\n" +
	"\rcontract_name\x18\x01 \x01(\tR\fcontractName\x12'\n" +
	"\x0fcontract_number\x18\x02 \x01(\tR\x0econtractNumber\x12+\n" +
	"\x11contract_deadline\x18\x03 \x01(\tR\x10contractDeadline\x12*\n" +
	"\x11contract_file_url\x18\x04 \x01(\tR\x0fcontractFileUrl\x12-\n" +
	"\x12responsible_person\x18\x05 \x01(\tR\x11responsiblePerson\"*\n" +
	"\x0eNewContractRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xae\x02\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcontract_name\x18\x02 \x01(\tR\fcontractName\x12'\n" +
	"\x0fcontract_number\x18\x03 \x01(\tR\x0econtractNumber\x12+\n" +
	"\x11contract_deadline\x18\x04 \x01(\tR\x10contractDeadline\x12*\n" +
	"\x11contract_file_url\x18\x05 \x01(\tR\x0fcontractFileUrl\x12-\n" +
	"\x12responsible_person\x18\x06 \x01(\tR\x11responsiblePerson\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xd9\x06\n" +
	"\x0fContractService\x12A\n" +
	"\vNewContract\x12\x18.contract.NewContractReq\x1a\x18.contract.NewContractRes\x12S\n" +
	"\x11NewContractUpdate\x12\x1e.contract.NewContractUpdateReq\x1a\x1e.contract.NewContractUpdateRes\x12S\n" +
	"\x11NewContractDelete\x12\x1e.contract.NewContractDeleteReq\x1a\x1e.contract.NewContractDeleteRes\x12V\n" +
	"\x12NewContractGetName\x12\x1f.contract.NewContractGetNameReq\x1a\x1f.contract.NewContractGetNameRes\x12S\n" +
	"\x11NewContractGetAll\x12\x1e.contract.NewContractGetAllReq\x1a\x1e.contract.NewContractGetAllRes\x12\\\n" +
	"\x14NewInsideTheContract\x12!.contract.NewInsideTheContractReq\x1a!.contract.NewInsideTheContractRes\x12n\n" +
	"\x1aNewInsideTheContractUpdate\x12'.contract.NewInsideTheContractUpdateReq\x1a'.contract.NewInsideTheContractUpdateRes\x12n\n" +
	"\x1aNewInsideTheContractDelete\x12'.contract.NewInsideTheContractDeleteReq\x1a'.contract.NewInsideTheContractDeleteRes\x12n\n" +
	"\x1aNewInsideTheContractGetAll\x12'.contract.NewInsideTheContractGetAllReq\x1a'.contract.NewInsideTheContractGetAllResB\x13Z\x11genproto/contractb\x06proto3"

var (
	file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescOnce sync.Once
	file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescData []byte
)

func file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescGZIP() []byte {
	file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescOnce.Do(func() {
		file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDesc), len(file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDesc)))
	})
	return file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDescData
}

var file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_goTypes = []any{
	(*NewInsideTheContractGetAllReq)(nil), // 0: contract.NewInsideTheContractGetAllReq
	(*NewInsideTheContractGetAllRes)(nil), // 1: contract.NewInsideTheContractGetAllRes
	(*NewInsideTheContractt)(nil),         // 2: contract.NewInsideTheContractt
	(*NewInsideTheContractDeleteReq)(nil), // 3: contract.NewInsideTheContractDeleteReq
	(*NewInsideTheContractDeleteRes)(nil), // 4: contract.NewInsideTheContractDeleteRes
	(*NewInsideTheContractUpdateReq)(nil), // 5: contract.NewInsideTheContractUpdateReq
	(*NewInsideTheContractUpdateRes)(nil), // 6: contract.NewInsideTheContractUpdateRes
	(*NewInsideTheContractReq)(nil),       // 7: contract.NewInsideTheContractReq
	(*NewInsideTheContractRes)(nil),       // 8: contract.NewInsideTheContractRes
	(*NewContractGetAllReq)(nil),          // 9: contract.NewContractGetAllReq
	(*NewContractGetAllRes)(nil),          // 10: contract.NewContractGetAllRes
	(*NewContractGetNameReq)(nil),         // 11: contract.NewContractGetNameReq
	(*NewContractGetNameRes)(nil),         // 12: contract.NewContractGetNameRes
	(*NewContractDeleteReq)(nil),          // 13: contract.NewContractDeleteReq
	(*NewContractDeleteRes)(nil),          // 14: contract.NewContractDeleteRes
	(*NewContractUpdateReq)(nil),          // 15: contract.NewContractUpdateReq
	(*NewContractUpdateRes)(nil),          // 16: contract.NewContractUpdateRes
	(*NewContractReq)(nil),                // 17: contract.NewContractReq
	(*NewContractRes)(nil),                // 18: contract.NewContractRes
	(*Contract)(nil),                      // 19: contract.Contract
}
var file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_depIdxs = []int32{
	2,  // 0: contract.NewInsideTheContractGetAllRes.all:type_name -> contract.NewInsideTheContractt
	19, // 1: contract.NewContractGetAllRes.contract:type_name -> contract.Contract
	17, // 2: contract.ContractService.NewContract:input_type -> contract.NewContractReq
	15, // 3: contract.ContractService.NewContractUpdate:input_type -> contract.NewContractUpdateReq
	13, // 4: contract.ContractService.NewContractDelete:input_type -> contract.NewContractDeleteReq
	11, // 5: contract.ContractService.NewContractGetName:input_type -> contract.NewContractGetNameReq
	9,  // 6: contract.ContractService.NewContractGetAll:input_type -> contract.NewContractGetAllReq
	7,  // 7: contract.ContractService.NewInsideTheContract:input_type -> contract.NewInsideTheContractReq
	5,  // 8: contract.ContractService.NewInsideTheContractUpdate:input_type -> contract.NewInsideTheContractUpdateReq
	3,  // 9: contract.ContractService.NewInsideTheContractDelete:input_type -> contract.NewInsideTheContractDeleteReq
	0,  // 10: contract.ContractService.NewInsideTheContractGetAll:input_type -> contract.NewInsideTheContractGetAllReq
	18, // 11: contract.ContractService.NewContract:output_type -> contract.NewContractRes
	16, // 12: contract.ContractService.NewContractUpdate:output_type -> contract.NewContractUpdateRes
	14, // 13: contract.ContractService.NewContractDelete:output_type -> contract.NewContractDeleteRes
	12, // 14: contract.ContractService.NewContractGetName:output_type -> contract.NewContractGetNameRes
	10, // 15: contract.ContractService.NewContractGetAll:output_type -> contract.NewContractGetAllRes
	8,  // 16: contract.ContractService.NewInsideTheContract:output_type -> contract.NewInsideTheContractRes
	6,  // 17: contract.ContractService.NewInsideTheContractUpdate:output_type -> contract.NewInsideTheContractUpdateRes
	4,  // 18: contract.ContractService.NewInsideTheContractDelete:output_type -> contract.NewInsideTheContractDeleteRes
	1,  // 19: contract.ContractService.NewInsideTheContractGetAll:output_type -> contract.NewInsideTheContractGetAllRes
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_init() }
func file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_init() {
	if File_ner_apk_proto_ishlab_chiqarish_shartnoma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDesc), len(file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_goTypes,
		DependencyIndexes: file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_depIdxs,
		MessageInfos:      file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_msgTypes,
	}.Build()
	File_ner_apk_proto_ishlab_chiqarish_shartnoma_proto = out.File
	file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_goTypes = nil
	file_ner_apk_proto_ishlab_chiqarish_shartnoma_proto_depIdxs = nil
}
