// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ner-apk-proto/ishlab_chiqarish/shartnoma.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractService_NewContract_FullMethodName                = "/contract.ContractService/NewContract"
	ContractService_NewContractUpdate_FullMethodName          = "/contract.ContractService/NewContractUpdate"
	ContractService_NewContractDelete_FullMethodName          = "/contract.ContractService/NewContractDelete"
	ContractService_NewContractGetName_FullMethodName         = "/contract.ContractService/NewContractGetName"
	ContractService_NewContractGetAll_FullMethodName          = "/contract.ContractService/NewContractGetAll"
	ContractService_NewInsideTheContract_FullMethodName       = "/contract.ContractService/NewInsideTheContract"
	ContractService_NewInsideTheContractUpdate_FullMethodName = "/contract.ContractService/NewInsideTheContractUpdate"
	ContractService_NewInsideTheContractDelete_FullMethodName = "/contract.ContractService/NewInsideTheContractDelete"
	ContractService_NewInsideTheContractGetAll_FullMethodName = "/contract.ContractService/NewInsideTheContractGetAll"
)

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractServiceClient interface {
	NewContract(ctx context.Context, in *NewContractReq, opts ...grpc.CallOption) (*NewContractRes, error)
	NewContractUpdate(ctx context.Context, in *NewContractUpdateReq, opts ...grpc.CallOption) (*NewContractUpdateRes, error)
	NewContractDelete(ctx context.Context, in *NewContractDeleteReq, opts ...grpc.CallOption) (*NewContractDeleteRes, error)
	NewContractGetName(ctx context.Context, in *NewContractGetNameReq, opts ...grpc.CallOption) (*NewContractGetNameRes, error)
	NewContractGetAll(ctx context.Context, in *NewContractGetAllReq, opts ...grpc.CallOption) (*NewContractGetAllRes, error)
	NewInsideTheContract(ctx context.Context, in *NewInsideTheContractReq, opts ...grpc.CallOption) (*NewInsideTheContractRes, error)
	NewInsideTheContractUpdate(ctx context.Context, in *NewInsideTheContractUpdateReq, opts ...grpc.CallOption) (*NewInsideTheContractUpdateRes, error)
	NewInsideTheContractDelete(ctx context.Context, in *NewInsideTheContractDeleteReq, opts ...grpc.CallOption) (*NewInsideTheContractDeleteRes, error)
	NewInsideTheContractGetAll(ctx context.Context, in *NewInsideTheContractGetAllReq, opts ...grpc.CallOption) (*NewInsideTheContractGetAllRes, error)
}

type contractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractServiceClient(cc grpc.ClientConnInterface) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) NewContract(ctx context.Context, in *NewContractReq, opts ...grpc.CallOption) (*NewContractRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractRes)
	err := c.cc.Invoke(ctx, ContractService_NewContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewContractUpdate(ctx context.Context, in *NewContractUpdateReq, opts ...grpc.CallOption) (*NewContractUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractUpdateRes)
	err := c.cc.Invoke(ctx, ContractService_NewContractUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewContractDelete(ctx context.Context, in *NewContractDeleteReq, opts ...grpc.CallOption) (*NewContractDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractDeleteRes)
	err := c.cc.Invoke(ctx, ContractService_NewContractDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewContractGetName(ctx context.Context, in *NewContractGetNameReq, opts ...grpc.CallOption) (*NewContractGetNameRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractGetNameRes)
	err := c.cc.Invoke(ctx, ContractService_NewContractGetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewContractGetAll(ctx context.Context, in *NewContractGetAllReq, opts ...grpc.CallOption) (*NewContractGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractGetAllRes)
	err := c.cc.Invoke(ctx, ContractService_NewContractGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewInsideTheContract(ctx context.Context, in *NewInsideTheContractReq, opts ...grpc.CallOption) (*NewInsideTheContractRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractRes)
	err := c.cc.Invoke(ctx, ContractService_NewInsideTheContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewInsideTheContractUpdate(ctx context.Context, in *NewInsideTheContractUpdateReq, opts ...grpc.CallOption) (*NewInsideTheContractUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractUpdateRes)
	err := c.cc.Invoke(ctx, ContractService_NewInsideTheContractUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewInsideTheContractDelete(ctx context.Context, in *NewInsideTheContractDeleteReq, opts ...grpc.CallOption) (*NewInsideTheContractDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractDeleteRes)
	err := c.cc.Invoke(ctx, ContractService_NewInsideTheContractDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NewInsideTheContractGetAll(ctx context.Context, in *NewInsideTheContractGetAllReq, opts ...grpc.CallOption) (*NewInsideTheContractGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractGetAllRes)
	err := c.cc.Invoke(ctx, ContractService_NewInsideTheContractGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServiceServer is the server API for ContractService service.
// All implementations must embed UnimplementedContractServiceServer
// for forward compatibility.
type ContractServiceServer interface {
	NewContract(context.Context, *NewContractReq) (*NewContractRes, error)
	NewContractUpdate(context.Context, *NewContractUpdateReq) (*NewContractUpdateRes, error)
	NewContractDelete(context.Context, *NewContractDeleteReq) (*NewContractDeleteRes, error)
	NewContractGetName(context.Context, *NewContractGetNameReq) (*NewContractGetNameRes, error)
	NewContractGetAll(context.Context, *NewContractGetAllReq) (*NewContractGetAllRes, error)
	NewInsideTheContract(context.Context, *NewInsideTheContractReq) (*NewInsideTheContractRes, error)
	NewInsideTheContractUpdate(context.Context, *NewInsideTheContractUpdateReq) (*NewInsideTheContractUpdateRes, error)
	NewInsideTheContractDelete(context.Context, *NewInsideTheContractDeleteReq) (*NewInsideTheContractDeleteRes, error)
	NewInsideTheContractGetAll(context.Context, *NewInsideTheContractGetAllReq) (*NewInsideTheContractGetAllRes, error)
	mustEmbedUnimplementedContractServiceServer()
}

// UnimplementedContractServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractServiceServer struct{}

func (UnimplementedContractServiceServer) NewContract(context.Context, *NewContractReq) (*NewContractRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContract not implemented")
}
func (UnimplementedContractServiceServer) NewContractUpdate(context.Context, *NewContractUpdateReq) (*NewContractUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractUpdate not implemented")
}
func (UnimplementedContractServiceServer) NewContractDelete(context.Context, *NewContractDeleteReq) (*NewContractDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractDelete not implemented")
}
func (UnimplementedContractServiceServer) NewContractGetName(context.Context, *NewContractGetNameReq) (*NewContractGetNameRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractGetName not implemented")
}
func (UnimplementedContractServiceServer) NewContractGetAll(context.Context, *NewContractGetAllReq) (*NewContractGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractGetAll not implemented")
}
func (UnimplementedContractServiceServer) NewInsideTheContract(context.Context, *NewInsideTheContractReq) (*NewInsideTheContractRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContract not implemented")
}
func (UnimplementedContractServiceServer) NewInsideTheContractUpdate(context.Context, *NewInsideTheContractUpdateReq) (*NewInsideTheContractUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractUpdate not implemented")
}
func (UnimplementedContractServiceServer) NewInsideTheContractDelete(context.Context, *NewInsideTheContractDeleteReq) (*NewInsideTheContractDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractDelete not implemented")
}
func (UnimplementedContractServiceServer) NewInsideTheContractGetAll(context.Context, *NewInsideTheContractGetAllReq) (*NewInsideTheContractGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractGetAll not implemented")
}
func (UnimplementedContractServiceServer) mustEmbedUnimplementedContractServiceServer() {}
func (UnimplementedContractServiceServer) testEmbeddedByValue()                         {}

// UnsafeContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractServiceServer will
// result in compilation errors.
type UnsafeContractServiceServer interface {
	mustEmbedUnimplementedContractServiceServer()
}

func RegisterContractServiceServer(s grpc.ServiceRegistrar, srv ContractServiceServer) {
	// If the following call pancis, it indicates UnimplementedContractServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractService_ServiceDesc, srv)
}

func _ContractService_NewContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewContract(ctx, req.(*NewContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewContractUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewContractUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewContractUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewContractUpdate(ctx, req.(*NewContractUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewContractDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewContractDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewContractDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewContractDelete(ctx, req.(*NewContractDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewContractGetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractGetNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewContractGetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewContractGetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewContractGetName(ctx, req.(*NewContractGetNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewContractGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewContractGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewContractGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewContractGetAll(ctx, req.(*NewContractGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewInsideTheContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewInsideTheContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewInsideTheContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewInsideTheContract(ctx, req.(*NewInsideTheContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewInsideTheContractUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewInsideTheContractUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewInsideTheContractUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewInsideTheContractUpdate(ctx, req.(*NewInsideTheContractUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewInsideTheContractDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewInsideTheContractDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewInsideTheContractDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewInsideTheContractDelete(ctx, req.(*NewInsideTheContractDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NewInsideTheContractGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NewInsideTheContractGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NewInsideTheContractGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NewInsideTheContractGetAll(ctx, req.(*NewInsideTheContractGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractService_ServiceDesc is the grpc.ServiceDesc for ContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewContract",
			Handler:    _ContractService_NewContract_Handler,
		},
		{
			MethodName: "NewContractUpdate",
			Handler:    _ContractService_NewContractUpdate_Handler,
		},
		{
			MethodName: "NewContractDelete",
			Handler:    _ContractService_NewContractDelete_Handler,
		},
		{
			MethodName: "NewContractGetName",
			Handler:    _ContractService_NewContractGetName_Handler,
		},
		{
			MethodName: "NewContractGetAll",
			Handler:    _ContractService_NewContractGetAll_Handler,
		},
		{
			MethodName: "NewInsideTheContract",
			Handler:    _ContractService_NewInsideTheContract_Handler,
		},
		{
			MethodName: "NewInsideTheContractUpdate",
			Handler:    _ContractService_NewInsideTheContractUpdate_Handler,
		},
		{
			MethodName: "NewInsideTheContractDelete",
			Handler:    _ContractService_NewInsideTheContractDelete_Handler,
		},
		{
			MethodName: "NewInsideTheContractGetAll",
			Handler:    _ContractService_NewInsideTheContractGetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ner-apk-proto/ishlab_chiqarish/shartnoma.proto",
}
