// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.2
// source: ner-apk-proto/ishlab_chiqarish/services.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////////////////// GROUP ////////////////////
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Master        string                 `protobuf:"bytes,3,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Master        string                 `protobuf:"bytes,2,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type CreateGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRes) Reset() {
	*x = CreateGroupRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRes) ProtoMessage() {}

func (x *CreateGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRes.ProtoReflect.Descriptor instead.
func (*CreateGroupRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Master        string                 `protobuf:"bytes,3,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupReq) Reset() {
	*x = UpdateGroupReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupReq) ProtoMessage() {}

func (x *UpdateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGroupReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupReq) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type UpdateGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRes) Reset() {
	*x = UpdateGroupRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRes) ProtoMessage() {}

func (x *UpdateGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRes.ProtoReflect.Descriptor instead.
func (*UpdateGroupRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupReq) Reset() {
	*x = DeleteGroupReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupReq) ProtoMessage() {}

func (x *DeleteGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteGroupReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGroupReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRes) Reset() {
	*x = DeleteGroupRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRes) ProtoMessage() {}

func (x *DeleteGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRes.ProtoReflect.Descriptor instead.
func (*DeleteGroupRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGroupReq) Reset() {
	*x = GetAllGroupReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupReq) ProtoMessage() {}

func (x *GetAllGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupReq.ProtoReflect.Descriptor instead.
func (*GetAllGroupReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllGroupReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllGroupReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGroupRes) Reset() {
	*x = GetAllGroupRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupRes) ProtoMessage() {}

func (x *GetAllGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupRes.ProtoReflect.Descriptor instead.
func (*GetAllGroupRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllGroupRes) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

// ////////////////// WORKER ////////////////////
type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{9}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Worker) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type CreateWorkerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerReq) Reset() {
	*x = CreateWorkerReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerReq) ProtoMessage() {}

func (x *CreateWorkerReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerReq.ProtoReflect.Descriptor instead.
func (*CreateWorkerReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{10}
}

func (x *CreateWorkerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkerReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateWorkerReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type CreateWorkerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerRes) Reset() {
	*x = CreateWorkerRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRes) ProtoMessage() {}

func (x *CreateWorkerRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRes.ProtoReflect.Descriptor instead.
func (*CreateWorkerRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{11}
}

func (x *CreateWorkerRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateWorkerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkerReq) Reset() {
	*x = UpdateWorkerReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerReq) ProtoMessage() {}

func (x *UpdateWorkerReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerReq.ProtoReflect.Descriptor instead.
func (*UpdateWorkerReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateWorkerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkerReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateWorkerReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type UpdateWorkerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkerRes) Reset() {
	*x = UpdateWorkerRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerRes) ProtoMessage() {}

func (x *UpdateWorkerRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerRes.ProtoReflect.Descriptor instead.
func (*UpdateWorkerRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorkerRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteWorkerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkerReq) Reset() {
	*x = DeleteWorkerReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkerReq) ProtoMessage() {}

func (x *DeleteWorkerReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkerReq.ProtoReflect.Descriptor instead.
func (*DeleteWorkerReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteWorkerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkerRes) Reset() {
	*x = DeleteWorkerRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkerRes) ProtoMessage() {}

func (x *DeleteWorkerRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkerRes.ProtoReflect.Descriptor instead.
func (*DeleteWorkerRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteWorkerRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllWorkerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWorkerReq) Reset() {
	*x = GetAllWorkerReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWorkerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWorkerReq) ProtoMessage() {}

func (x *GetAllWorkerReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWorkerReq.ProtoReflect.Descriptor instead.
func (*GetAllWorkerReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllWorkerReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllWorkerReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllWorkerReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetAllWorkerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWorkerRes) Reset() {
	*x = GetAllWorkerRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWorkerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWorkerRes) ProtoMessage() {}

func (x *GetAllWorkerRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWorkerRes.ProtoReflect.Descriptor instead.
func (*GetAllWorkerRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllWorkerRes) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

// ////////////////// ATTENDANCE ////////////////////
type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Situation     string                 `protobuf:"bytes,2,opt,name=situation,proto3" json:"situation,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	IsPresent     bool                   `protobuf:"varint,4,opt,name=is_present,json=isPresent,proto3" json:"is_present,omitempty"`
	WorkDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=work_date,json=workDate,proto3" json:"work_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{18}
}

func (x *Attendance) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Attendance) GetSituation() string {
	if x != nil {
		return x.Situation
	}
	return ""
}

func (x *Attendance) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Attendance) GetIsPresent() bool {
	if x != nil {
		return x.IsPresent
	}
	return false
}

func (x *Attendance) GetWorkDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WorkDate
	}
	return nil
}

type CreateAttendanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    []*Attendance          `protobuf:"bytes,1,rep,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttendanceReq) Reset() {
	*x = CreateAttendanceReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttendanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttendanceReq) ProtoMessage() {}

func (x *CreateAttendanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttendanceReq.ProtoReflect.Descriptor instead.
func (*CreateAttendanceReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAttendanceReq) GetAttendance() []*Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

type CreateAttendanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttendanceRes) Reset() {
	*x = CreateAttendanceRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttendanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttendanceRes) ProtoMessage() {}

func (x *CreateAttendanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttendanceRes.ProtoReflect.Descriptor instead.
func (*CreateAttendanceRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{20}
}

func (x *CreateAttendanceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAttendanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    []*Attendance          `protobuf:"bytes,1,rep,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttendanceReq) Reset() {
	*x = UpdateAttendanceReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttendanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttendanceReq) ProtoMessage() {}

func (x *UpdateAttendanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttendanceReq.ProtoReflect.Descriptor instead.
func (*UpdateAttendanceReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateAttendanceReq) GetAttendance() []*Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

type UpdateAttendanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttendanceRes) Reset() {
	*x = UpdateAttendanceRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttendanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttendanceRes) ProtoMessage() {}

func (x *UpdateAttendanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttendanceRes.ProtoReflect.Descriptor instead.
func (*UpdateAttendanceRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateAttendanceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAttendanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkDate      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=work_date,json=workDate,proto3" json:"work_date,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttendanceReq) Reset() {
	*x = DeleteAttendanceReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttendanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttendanceReq) ProtoMessage() {}

func (x *DeleteAttendanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttendanceReq.ProtoReflect.Descriptor instead.
func (*DeleteAttendanceReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAttendanceReq) GetWorkDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WorkDate
	}
	return nil
}

func (x *DeleteAttendanceReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteAttendanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttendanceRes) Reset() {
	*x = DeleteAttendanceRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttendanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttendanceRes) ProtoMessage() {}

func (x *DeleteAttendanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttendanceRes.ProtoReflect.Descriptor instead.
func (*DeleteAttendanceRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteAttendanceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDailyAttendanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkDate      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=work_date,json=workDate,proto3" json:"work_date,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyAttendanceReq) Reset() {
	*x = GetDailyAttendanceReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyAttendanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyAttendanceReq) ProtoMessage() {}

func (x *GetDailyAttendanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyAttendanceReq.ProtoReflect.Descriptor instead.
func (*GetDailyAttendanceReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{25}
}

func (x *GetDailyAttendanceReq) GetWorkDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WorkDate
	}
	return nil
}

func (x *GetDailyAttendanceReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetDailyAttendanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    []*Attendance          `protobuf:"bytes,1,rep,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyAttendanceRes) Reset() {
	*x = GetDailyAttendanceRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyAttendanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyAttendanceRes) ProtoMessage() {}

func (x *GetDailyAttendanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyAttendanceRes.ProtoReflect.Descriptor instead.
func (*GetDailyAttendanceRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{26}
}

func (x *GetDailyAttendanceRes) GetAttendance() []*Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

type GetAllAttendanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAttendanceReq) Reset() {
	*x = GetAllAttendanceReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAttendanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAttendanceReq) ProtoMessage() {}

func (x *GetAllAttendanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAttendanceReq.ProtoReflect.Descriptor instead.
func (*GetAllAttendanceReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{27}
}

func (x *GetAllAttendanceReq) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAllAttendanceReq) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetAllAttendanceReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetAllAttendanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    []*Attendance          `protobuf:"bytes,1,rep,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAttendanceRes) Reset() {
	*x = GetAllAttendanceRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAttendanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAttendanceRes) ProtoMessage() {}

func (x *GetAllAttendanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAttendanceRes.ProtoReflect.Descriptor instead.
func (*GetAllAttendanceRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{28}
}

func (x *GetAllAttendanceRes) GetAttendance() []*Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

// ////////////////// TASK ////////////////////
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{29}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Task) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Task) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Task) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{30}
}

func (x *CreateTaskReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateTaskReq) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *CreateTaskReq) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CreateTaskReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateTaskReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRes) Reset() {
	*x = CreateTaskRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRes) ProtoMessage() {}

func (x *CreateTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRes.ProtoReflect.Descriptor instead.
func (*CreateTaskRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{31}
}

func (x *CreateTaskRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskReq) Reset() {
	*x = UpdateTaskReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskReq) ProtoMessage() {}

func (x *UpdateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskReq.ProtoReflect.Descriptor instead.
func (*UpdateTaskReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *UpdateTaskReq) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpdateTaskReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type UpdateTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRes) Reset() {
	*x = UpdateTaskRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRes) ProtoMessage() {}

func (x *UpdateTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRes.ProtoReflect.Descriptor instead.
func (*UpdateTaskRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateTaskRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskReq) Reset() {
	*x = DeleteTaskReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskReq) ProtoMessage() {}

func (x *DeleteTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskReq.ProtoReflect.Descriptor instead.
func (*DeleteTaskReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRes) Reset() {
	*x = DeleteTaskRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRes) ProtoMessage() {}

func (x *DeleteTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRes.ProtoReflect.Descriptor instead.
func (*DeleteTaskRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteTaskRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTaskReq) Reset() {
	*x = GetAllTaskReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTaskReq) ProtoMessage() {}

func (x *GetAllTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTaskReq.ProtoReflect.Descriptor instead.
func (*GetAllTaskReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{36}
}

func (x *GetAllTaskReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetAllTaskReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllTaskReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTaskRes) Reset() {
	*x = GetAllTaskRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTaskRes) ProtoMessage() {}

func (x *GetAllTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTaskRes.ProtoReflect.Descriptor instead.
func (*GetAllTaskRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{37}
}

func (x *GetAllTaskRes) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIdReq) Reset() {
	*x = GetTaskByIdReq{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdReq) ProtoMessage() {}

func (x *GetTaskByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdReq.ProtoReflect.Descriptor instead.
func (*GetTaskByIdReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{38}
}

func (x *GetTaskByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIdRes) Reset() {
	*x = GetTaskByIdRes{}
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdRes) ProtoMessage() {}

func (x *GetTaskByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdRes.ProtoReflect.Descriptor instead.
func (*GetTaskByIdRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP(), []int{39}
}

func (x *GetTaskByIdRes) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_ner_apk_proto_ishlab_chiqarish_services_proto protoreflect.FileDescriptor

const file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDesc = "" +
	"\n" +
	"-ner-apk-proto/ishlab_chiqarish/services.proto\x12\bservices\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06master\x18\x03 \x01(\tR\x06master\"<\n" +
	"\x0eCreateGroupReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06master\x18\x02 \x01(\tR\x06master\"*\n" +
	"\x0eCreateGroupRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\x0eUpdateGroupReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06master\x18\x03 \x01(\tR\x06master\"*\n" +
	"\x0eUpdateGroupRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\x0eDeleteGroupReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eDeleteGroupRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x0eGetAllGroupReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\"9\n" +
	"\x0eGetAllGroupRes\x12'\n" +
	"\x06groups\x18\x01 \x03(\v2\x0f.services.GroupR\x06groups\"]\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\"V\n" +
	"\x0fCreateWorkerReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\"+\n" +
	"\x0fCreateWorkerRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"f\n" +
	"\x0fUpdateWorkerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\"+\n" +
	"\x0fUpdateWorkerRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x0fDeleteWorkerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fDeleteWorkerRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\x0fGetAllWorkerReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\"=\n" +
	"\x0fGetAllWorkerRes\x12*\n" +
	"\aworkers\x18\x01 \x03(\v2\x10.services.WorkerR\aworkers\"\xb7\x01\n" +
	"\n" +
	"Attendance\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\tsituation\x18\x02 \x01(\tR\tsituation\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"is_present\x18\x04 \x01(\bR\tisPresent\x127\n" +
	"\twork_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bworkDate\"K\n" +
	"\x13CreateAttendanceReq\x124\n" +
	"\n" +
	"attendance\x18\x01 \x03(\v2\x14.services.AttendanceR\n" +
	"attendance\"/\n" +
	"\x13CreateAttendanceRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x13UpdateAttendanceReq\x124\n" +
	"\n" +
	"attendance\x18\x01 \x03(\v2\x14.services.AttendanceR\n" +
	"attendance\"/\n" +
	"\x13UpdateAttendanceRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"i\n" +
	"\x13DeleteAttendanceReq\x127\n" +
	"\twork_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bworkDate\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"/\n" +
	"\x13DeleteAttendanceRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"k\n" +
	"\x15GetDailyAttendanceReq\x127\n" +
	"\twork_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bworkDate\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"M\n" +
	"\x15GetDailyAttendanceRes\x124\n" +
	"\n" +
	"attendance\x18\x01 \x03(\v2\x14.services.AttendanceR\n" +
	"attendance\"\xa2\x01\n" +
	"\x13GetAllAttendanceReq\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\"K\n" +
	"\x13GetAllAttendanceRes\x124\n" +
	"\n" +
	"attendance\x18\x01 \x03(\v2\x14.services.AttendanceR\n" +
	"attendance\"\xf1\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xea\x01\n" +
	"\rCreateTaskReq\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\")\n" +
	"\rCreateTaskRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xab\x01\n" +
	"\rUpdateTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\")\n" +
	"\rUpdateTaskRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1f\n" +
	"\rDeleteTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rDeleteTaskRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\rGetAllTaskReq\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\"5\n" +
	"\rGetAllTaskRes\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.services.TaskR\x05tasks\" \n" +
	"\x0eGetTaskByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0eGetTaskByIdRes\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.services.TaskR\x04task2\x98\n" +
	"\n" +
	"\x0fServicesService\x12A\n" +
	"\vCreateGroup\x12\x18.services.CreateGroupReq\x1a\x18.services.CreateGroupRes\x12A\n" +
	"\vUpdateGroup\x12\x18.services.UpdateGroupReq\x1a\x18.services.UpdateGroupRes\x12A\n" +
	"\vDeleteGroup\x12\x18.services.DeleteGroupReq\x1a\x18.services.DeleteGroupRes\x12A\n" +
	"\vGetAllGroup\x12\x18.services.GetAllGroupReq\x1a\x18.services.GetAllGroupRes\x12D\n" +
	"\fCreateWorker\x12\x19.services.CreateWorkerReq\x1a\x19.services.CreateWorkerRes\x12D\n" +
	"\fUpdateWorker\x12\x19.services.UpdateWorkerReq\x1a\x19.services.UpdateWorkerRes\x12D\n" +
	"\fDeleteWorker\x12\x19.services.DeleteWorkerReq\x1a\x19.services.DeleteWorkerRes\x12D\n" +
	"\fGetAllWorker\x12\x19.services.GetAllWorkerReq\x1a\x19.services.GetAllWorkerRes\x12P\n" +
	"\x10CreateAttendance\x12\x1d.services.CreateAttendanceReq\x1a\x1d.services.CreateAttendanceRes\x12P\n" +
	"\x10UpdateAttendance\x12\x1d.services.UpdateAttendanceReq\x1a\x1d.services.UpdateAttendanceRes\x12P\n" +
	"\x10DeleteAttendance\x12\x1d.services.DeleteAttendanceReq\x1a\x1d.services.DeleteAttendanceRes\x12V\n" +
	"\x12GetDailyAttendance\x12\x1f.services.GetDailyAttendanceReq\x1a\x1f.services.GetDailyAttendanceRes\x12P\n" +
	"\x10GetAllAttendance\x12\x1d.services.GetAllAttendanceReq\x1a\x1d.services.GetAllAttendanceRes\x12>\n" +
	"\n" +
	"CreateTask\x12\x17.services.CreateTaskReq\x1a\x17.services.CreateTaskRes\x12>\n" +
	"\n" +
	"UpdateTask\x12\x17.services.UpdateTaskReq\x1a\x17.services.UpdateTaskRes\x12>\n" +
	"\n" +
	"DeleteTask\x12\x17.services.DeleteTaskReq\x1a\x17.services.DeleteTaskRes\x12>\n" +
	"\n" +
	"GetAllTask\x12\x17.services.GetAllTaskReq\x1a\x17.services.GetAllTaskRes\x12A\n" +
	"\vGetTaskById\x12\x18.services.GetTaskByIdReq\x1a\x18.services.GetTaskByIdResB\x13Z\x11genproto/servicesb\x06proto3"

var (
	file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescOnce sync.Once
	file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescData []byte
)

func file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescGZIP() []byte {
	file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescOnce.Do(func() {
		file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDesc), len(file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDesc)))
	})
	return file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDescData
}

var file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_ner_apk_proto_ishlab_chiqarish_services_proto_goTypes = []any{
	(*Group)(nil),                 // 0: services.Group
	(*CreateGroupReq)(nil),        // 1: services.CreateGroupReq
	(*CreateGroupRes)(nil),        // 2: services.CreateGroupRes
	(*UpdateGroupReq)(nil),        // 3: services.UpdateGroupReq
	(*UpdateGroupRes)(nil),        // 4: services.UpdateGroupRes
	(*DeleteGroupReq)(nil),        // 5: services.DeleteGroupReq
	(*DeleteGroupRes)(nil),        // 6: services.DeleteGroupRes
	(*GetAllGroupReq)(nil),        // 7: services.GetAllGroupReq
	(*GetAllGroupRes)(nil),        // 8: services.GetAllGroupRes
	(*Worker)(nil),                // 9: services.Worker
	(*CreateWorkerReq)(nil),       // 10: services.CreateWorkerReq
	(*CreateWorkerRes)(nil),       // 11: services.CreateWorkerRes
	(*UpdateWorkerReq)(nil),       // 12: services.UpdateWorkerReq
	(*UpdateWorkerRes)(nil),       // 13: services.UpdateWorkerRes
	(*DeleteWorkerReq)(nil),       // 14: services.DeleteWorkerReq
	(*DeleteWorkerRes)(nil),       // 15: services.DeleteWorkerRes
	(*GetAllWorkerReq)(nil),       // 16: services.GetAllWorkerReq
	(*GetAllWorkerRes)(nil),       // 17: services.GetAllWorkerRes
	(*Attendance)(nil),            // 18: services.Attendance
	(*CreateAttendanceReq)(nil),   // 19: services.CreateAttendanceReq
	(*CreateAttendanceRes)(nil),   // 20: services.CreateAttendanceRes
	(*UpdateAttendanceReq)(nil),   // 21: services.UpdateAttendanceReq
	(*UpdateAttendanceRes)(nil),   // 22: services.UpdateAttendanceRes
	(*DeleteAttendanceReq)(nil),   // 23: services.DeleteAttendanceReq
	(*DeleteAttendanceRes)(nil),   // 24: services.DeleteAttendanceRes
	(*GetDailyAttendanceReq)(nil), // 25: services.GetDailyAttendanceReq
	(*GetDailyAttendanceRes)(nil), // 26: services.GetDailyAttendanceRes
	(*GetAllAttendanceReq)(nil),   // 27: services.GetAllAttendanceReq
	(*GetAllAttendanceRes)(nil),   // 28: services.GetAllAttendanceRes
	(*Task)(nil),                  // 29: services.Task
	(*CreateTaskReq)(nil),         // 30: services.CreateTaskReq
	(*CreateTaskRes)(nil),         // 31: services.CreateTaskRes
	(*UpdateTaskReq)(nil),         // 32: services.UpdateTaskReq
	(*UpdateTaskRes)(nil),         // 33: services.UpdateTaskRes
	(*DeleteTaskReq)(nil),         // 34: services.DeleteTaskReq
	(*DeleteTaskRes)(nil),         // 35: services.DeleteTaskRes
	(*GetAllTaskReq)(nil),         // 36: services.GetAllTaskReq
	(*GetAllTaskRes)(nil),         // 37: services.GetAllTaskRes
	(*GetTaskByIdReq)(nil),        // 38: services.GetTaskByIdReq
	(*GetTaskByIdRes)(nil),        // 39: services.GetTaskByIdRes
	(*timestamppb.Timestamp)(nil), // 40: google.protobuf.Timestamp
}
var file_ner_apk_proto_ishlab_chiqarish_services_proto_depIdxs = []int32{
	0,  // 0: services.GetAllGroupRes.groups:type_name -> services.Group
	9,  // 1: services.GetAllWorkerRes.workers:type_name -> services.Worker
	40, // 2: services.Attendance.work_date:type_name -> google.protobuf.Timestamp
	18, // 3: services.CreateAttendanceReq.attendance:type_name -> services.Attendance
	18, // 4: services.UpdateAttendanceReq.attendance:type_name -> services.Attendance
	40, // 5: services.DeleteAttendanceReq.work_date:type_name -> google.protobuf.Timestamp
	40, // 6: services.GetDailyAttendanceReq.work_date:type_name -> google.protobuf.Timestamp
	18, // 7: services.GetDailyAttendanceRes.attendance:type_name -> services.Attendance
	40, // 8: services.GetAllAttendanceReq.start_date:type_name -> google.protobuf.Timestamp
	40, // 9: services.GetAllAttendanceReq.end_date:type_name -> google.protobuf.Timestamp
	18, // 10: services.GetAllAttendanceRes.attendance:type_name -> services.Attendance
	40, // 11: services.Task.deadline:type_name -> google.protobuf.Timestamp
	40, // 12: services.Task.start_time:type_name -> google.protobuf.Timestamp
	40, // 13: services.Task.end_time:type_name -> google.protobuf.Timestamp
	40, // 14: services.CreateTaskReq.deadline:type_name -> google.protobuf.Timestamp
	40, // 15: services.CreateTaskReq.start_time:type_name -> google.protobuf.Timestamp
	40, // 16: services.CreateTaskReq.end_time:type_name -> google.protobuf.Timestamp
	40, // 17: services.UpdateTaskReq.deadline:type_name -> google.protobuf.Timestamp
	40, // 18: services.UpdateTaskReq.end_time:type_name -> google.protobuf.Timestamp
	29, // 19: services.GetAllTaskRes.tasks:type_name -> services.Task
	29, // 20: services.GetTaskByIdRes.task:type_name -> services.Task
	1,  // 21: services.ServicesService.CreateGroup:input_type -> services.CreateGroupReq
	3,  // 22: services.ServicesService.UpdateGroup:input_type -> services.UpdateGroupReq
	5,  // 23: services.ServicesService.DeleteGroup:input_type -> services.DeleteGroupReq
	7,  // 24: services.ServicesService.GetAllGroup:input_type -> services.GetAllGroupReq
	10, // 25: services.ServicesService.CreateWorker:input_type -> services.CreateWorkerReq
	12, // 26: services.ServicesService.UpdateWorker:input_type -> services.UpdateWorkerReq
	14, // 27: services.ServicesService.DeleteWorker:input_type -> services.DeleteWorkerReq
	16, // 28: services.ServicesService.GetAllWorker:input_type -> services.GetAllWorkerReq
	19, // 29: services.ServicesService.CreateAttendance:input_type -> services.CreateAttendanceReq
	21, // 30: services.ServicesService.UpdateAttendance:input_type -> services.UpdateAttendanceReq
	23, // 31: services.ServicesService.DeleteAttendance:input_type -> services.DeleteAttendanceReq
	25, // 32: services.ServicesService.GetDailyAttendance:input_type -> services.GetDailyAttendanceReq
	27, // 33: services.ServicesService.GetAllAttendance:input_type -> services.GetAllAttendanceReq
	30, // 34: services.ServicesService.CreateTask:input_type -> services.CreateTaskReq
	32, // 35: services.ServicesService.UpdateTask:input_type -> services.UpdateTaskReq
	34, // 36: services.ServicesService.DeleteTask:input_type -> services.DeleteTaskReq
	36, // 37: services.ServicesService.GetAllTask:input_type -> services.GetAllTaskReq
	38, // 38: services.ServicesService.GetTaskById:input_type -> services.GetTaskByIdReq
	2,  // 39: services.ServicesService.CreateGroup:output_type -> services.CreateGroupRes
	4,  // 40: services.ServicesService.UpdateGroup:output_type -> services.UpdateGroupRes
	6,  // 41: services.ServicesService.DeleteGroup:output_type -> services.DeleteGroupRes
	8,  // 42: services.ServicesService.GetAllGroup:output_type -> services.GetAllGroupRes
	11, // 43: services.ServicesService.CreateWorker:output_type -> services.CreateWorkerRes
	13, // 44: services.ServicesService.UpdateWorker:output_type -> services.UpdateWorkerRes
	15, // 45: services.ServicesService.DeleteWorker:output_type -> services.DeleteWorkerRes
	17, // 46: services.ServicesService.GetAllWorker:output_type -> services.GetAllWorkerRes
	20, // 47: services.ServicesService.CreateAttendance:output_type -> services.CreateAttendanceRes
	22, // 48: services.ServicesService.UpdateAttendance:output_type -> services.UpdateAttendanceRes
	24, // 49: services.ServicesService.DeleteAttendance:output_type -> services.DeleteAttendanceRes
	26, // 50: services.ServicesService.GetDailyAttendance:output_type -> services.GetDailyAttendanceRes
	28, // 51: services.ServicesService.GetAllAttendance:output_type -> services.GetAllAttendanceRes
	31, // 52: services.ServicesService.CreateTask:output_type -> services.CreateTaskRes
	33, // 53: services.ServicesService.UpdateTask:output_type -> services.UpdateTaskRes
	35, // 54: services.ServicesService.DeleteTask:output_type -> services.DeleteTaskRes
	37, // 55: services.ServicesService.GetAllTask:output_type -> services.GetAllTaskRes
	39, // 56: services.ServicesService.GetTaskById:output_type -> services.GetTaskByIdRes
	39, // [39:57] is the sub-list for method output_type
	21, // [21:39] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ner_apk_proto_ishlab_chiqarish_services_proto_init() }
func file_ner_apk_proto_ishlab_chiqarish_services_proto_init() {
	if File_ner_apk_proto_ishlab_chiqarish_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDesc), len(file_ner_apk_proto_ishlab_chiqarish_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ner_apk_proto_ishlab_chiqarish_services_proto_goTypes,
		DependencyIndexes: file_ner_apk_proto_ishlab_chiqarish_services_proto_depIdxs,
		MessageInfos:      file_ner_apk_proto_ishlab_chiqarish_services_proto_msgTypes,
	}.Build()
	File_ner_apk_proto_ishlab_chiqarish_services_proto = out.File
	file_ner_apk_proto_ishlab_chiqarish_services_proto_goTypes = nil
	file_ner_apk_proto_ishlab_chiqarish_services_proto_depIdxs = nil
}
