// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ner-apk-proto/ishlab_chiqarish/services.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicesService_CreateGroup_FullMethodName        = "/services.ServicesService/CreateGroup"
	ServicesService_UpdateGroup_FullMethodName        = "/services.ServicesService/UpdateGroup"
	ServicesService_DeleteGroup_FullMethodName        = "/services.ServicesService/DeleteGroup"
	ServicesService_GetAllGroup_FullMethodName        = "/services.ServicesService/GetAllGroup"
	ServicesService_CreateWorker_FullMethodName       = "/services.ServicesService/CreateWorker"
	ServicesService_UpdateWorker_FullMethodName       = "/services.ServicesService/UpdateWorker"
	ServicesService_DeleteWorker_FullMethodName       = "/services.ServicesService/DeleteWorker"
	ServicesService_GetAllWorker_FullMethodName       = "/services.ServicesService/GetAllWorker"
	ServicesService_CreateAttendance_FullMethodName   = "/services.ServicesService/CreateAttendance"
	ServicesService_UpdateAttendance_FullMethodName   = "/services.ServicesService/UpdateAttendance"
	ServicesService_DeleteAttendance_FullMethodName   = "/services.ServicesService/DeleteAttendance"
	ServicesService_GetDailyAttendance_FullMethodName = "/services.ServicesService/GetDailyAttendance"
	ServicesService_GetAllAttendance_FullMethodName   = "/services.ServicesService/GetAllAttendance"
	ServicesService_CreateTask_FullMethodName         = "/services.ServicesService/CreateTask"
	ServicesService_UpdateTask_FullMethodName         = "/services.ServicesService/UpdateTask"
	ServicesService_DeleteTask_FullMethodName         = "/services.ServicesService/DeleteTask"
	ServicesService_GetAllTask_FullMethodName         = "/services.ServicesService/GetAllTask"
	ServicesService_GetTaskById_FullMethodName        = "/services.ServicesService/GetTaskById"
)

// ServicesServiceClient is the client API for ServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicesServiceClient interface {
	// GROUP
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupRes, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupRes, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*DeleteGroupRes, error)
	GetAllGroup(ctx context.Context, in *GetAllGroupReq, opts ...grpc.CallOption) (*GetAllGroupRes, error)
	// WORKER
	CreateWorker(ctx context.Context, in *CreateWorkerReq, opts ...grpc.CallOption) (*CreateWorkerRes, error)
	UpdateWorker(ctx context.Context, in *UpdateWorkerReq, opts ...grpc.CallOption) (*UpdateWorkerRes, error)
	DeleteWorker(ctx context.Context, in *DeleteWorkerReq, opts ...grpc.CallOption) (*DeleteWorkerRes, error)
	GetAllWorker(ctx context.Context, in *GetAllWorkerReq, opts ...grpc.CallOption) (*GetAllWorkerRes, error)
	// ATTENDANCE
	CreateAttendance(ctx context.Context, in *CreateAttendanceReq, opts ...grpc.CallOption) (*CreateAttendanceRes, error)
	UpdateAttendance(ctx context.Context, in *UpdateAttendanceReq, opts ...grpc.CallOption) (*UpdateAttendanceRes, error)
	DeleteAttendance(ctx context.Context, in *DeleteAttendanceReq, opts ...grpc.CallOption) (*DeleteAttendanceRes, error)
	GetDailyAttendance(ctx context.Context, in *GetDailyAttendanceReq, opts ...grpc.CallOption) (*GetDailyAttendanceRes, error)
	GetAllAttendance(ctx context.Context, in *GetAllAttendanceReq, opts ...grpc.CallOption) (*GetAllAttendanceRes, error)
	// TASK
	CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskRes, error)
	UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskRes, error)
	DeleteTask(ctx context.Context, in *DeleteTaskReq, opts ...grpc.CallOption) (*DeleteTaskRes, error)
	GetAllTask(ctx context.Context, in *GetAllTaskReq, opts ...grpc.CallOption) (*GetAllTaskRes, error)
	GetTaskById(ctx context.Context, in *GetTaskByIdReq, opts ...grpc.CallOption) (*GetTaskByIdRes, error)
}

type servicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesServiceClient(cc grpc.ClientConnInterface) ServicesServiceClient {
	return &servicesServiceClient{cc}
}

func (c *servicesServiceClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupRes)
	err := c.cc.Invoke(ctx, ServicesService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupRes)
	err := c.cc.Invoke(ctx, ServicesService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*DeleteGroupRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGroupRes)
	err := c.cc.Invoke(ctx, ServicesService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetAllGroup(ctx context.Context, in *GetAllGroupReq, opts ...grpc.CallOption) (*GetAllGroupRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGroupRes)
	err := c.cc.Invoke(ctx, ServicesService_GetAllGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) CreateWorker(ctx context.Context, in *CreateWorkerReq, opts ...grpc.CallOption) (*CreateWorkerRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkerRes)
	err := c.cc.Invoke(ctx, ServicesService_CreateWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) UpdateWorker(ctx context.Context, in *UpdateWorkerReq, opts ...grpc.CallOption) (*UpdateWorkerRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkerRes)
	err := c.cc.Invoke(ctx, ServicesService_UpdateWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) DeleteWorker(ctx context.Context, in *DeleteWorkerReq, opts ...grpc.CallOption) (*DeleteWorkerRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkerRes)
	err := c.cc.Invoke(ctx, ServicesService_DeleteWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetAllWorker(ctx context.Context, in *GetAllWorkerReq, opts ...grpc.CallOption) (*GetAllWorkerRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllWorkerRes)
	err := c.cc.Invoke(ctx, ServicesService_GetAllWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) CreateAttendance(ctx context.Context, in *CreateAttendanceReq, opts ...grpc.CallOption) (*CreateAttendanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttendanceRes)
	err := c.cc.Invoke(ctx, ServicesService_CreateAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) UpdateAttendance(ctx context.Context, in *UpdateAttendanceReq, opts ...grpc.CallOption) (*UpdateAttendanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAttendanceRes)
	err := c.cc.Invoke(ctx, ServicesService_UpdateAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) DeleteAttendance(ctx context.Context, in *DeleteAttendanceReq, opts ...grpc.CallOption) (*DeleteAttendanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAttendanceRes)
	err := c.cc.Invoke(ctx, ServicesService_DeleteAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetDailyAttendance(ctx context.Context, in *GetDailyAttendanceReq, opts ...grpc.CallOption) (*GetDailyAttendanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyAttendanceRes)
	err := c.cc.Invoke(ctx, ServicesService_GetDailyAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetAllAttendance(ctx context.Context, in *GetAllAttendanceReq, opts ...grpc.CallOption) (*GetAllAttendanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAttendanceRes)
	err := c.cc.Invoke(ctx, ServicesService_GetAllAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskRes)
	err := c.cc.Invoke(ctx, ServicesService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskRes)
	err := c.cc.Invoke(ctx, ServicesService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskReq, opts ...grpc.CallOption) (*DeleteTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskRes)
	err := c.cc.Invoke(ctx, ServicesService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetAllTask(ctx context.Context, in *GetAllTaskReq, opts ...grpc.CallOption) (*GetAllTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTaskRes)
	err := c.cc.Invoke(ctx, ServicesService_GetAllTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetTaskById(ctx context.Context, in *GetTaskByIdReq, opts ...grpc.CallOption) (*GetTaskByIdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskByIdRes)
	err := c.cc.Invoke(ctx, ServicesService_GetTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServiceServer is the server API for ServicesService service.
// All implementations must embed UnimplementedServicesServiceServer
// for forward compatibility.
type ServicesServiceServer interface {
	// GROUP
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupRes, error)
	UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupRes, error)
	DeleteGroup(context.Context, *DeleteGroupReq) (*DeleteGroupRes, error)
	GetAllGroup(context.Context, *GetAllGroupReq) (*GetAllGroupRes, error)
	// WORKER
	CreateWorker(context.Context, *CreateWorkerReq) (*CreateWorkerRes, error)
	UpdateWorker(context.Context, *UpdateWorkerReq) (*UpdateWorkerRes, error)
	DeleteWorker(context.Context, *DeleteWorkerReq) (*DeleteWorkerRes, error)
	GetAllWorker(context.Context, *GetAllWorkerReq) (*GetAllWorkerRes, error)
	// ATTENDANCE
	CreateAttendance(context.Context, *CreateAttendanceReq) (*CreateAttendanceRes, error)
	UpdateAttendance(context.Context, *UpdateAttendanceReq) (*UpdateAttendanceRes, error)
	DeleteAttendance(context.Context, *DeleteAttendanceReq) (*DeleteAttendanceRes, error)
	GetDailyAttendance(context.Context, *GetDailyAttendanceReq) (*GetDailyAttendanceRes, error)
	GetAllAttendance(context.Context, *GetAllAttendanceReq) (*GetAllAttendanceRes, error)
	// TASK
	CreateTask(context.Context, *CreateTaskReq) (*CreateTaskRes, error)
	UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskRes, error)
	DeleteTask(context.Context, *DeleteTaskReq) (*DeleteTaskRes, error)
	GetAllTask(context.Context, *GetAllTaskReq) (*GetAllTaskRes, error)
	GetTaskById(context.Context, *GetTaskByIdReq) (*GetTaskByIdRes, error)
	mustEmbedUnimplementedServicesServiceServer()
}

// UnimplementedServicesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicesServiceServer struct{}

func (UnimplementedServicesServiceServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedServicesServiceServer) UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedServicesServiceServer) DeleteGroup(context.Context, *DeleteGroupReq) (*DeleteGroupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedServicesServiceServer) GetAllGroup(context.Context, *GetAllGroupReq) (*GetAllGroupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGroup not implemented")
}
func (UnimplementedServicesServiceServer) CreateWorker(context.Context, *CreateWorkerReq) (*CreateWorkerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorker not implemented")
}
func (UnimplementedServicesServiceServer) UpdateWorker(context.Context, *UpdateWorkerReq) (*UpdateWorkerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorker not implemented")
}
func (UnimplementedServicesServiceServer) DeleteWorker(context.Context, *DeleteWorkerReq) (*DeleteWorkerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorker not implemented")
}
func (UnimplementedServicesServiceServer) GetAllWorker(context.Context, *GetAllWorkerReq) (*GetAllWorkerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllWorker not implemented")
}
func (UnimplementedServicesServiceServer) CreateAttendance(context.Context, *CreateAttendanceReq) (*CreateAttendanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttendance not implemented")
}
func (UnimplementedServicesServiceServer) UpdateAttendance(context.Context, *UpdateAttendanceReq) (*UpdateAttendanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttendance not implemented")
}
func (UnimplementedServicesServiceServer) DeleteAttendance(context.Context, *DeleteAttendanceReq) (*DeleteAttendanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttendance not implemented")
}
func (UnimplementedServicesServiceServer) GetDailyAttendance(context.Context, *GetDailyAttendanceReq) (*GetDailyAttendanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyAttendance not implemented")
}
func (UnimplementedServicesServiceServer) GetAllAttendance(context.Context, *GetAllAttendanceReq) (*GetAllAttendanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAttendance not implemented")
}
func (UnimplementedServicesServiceServer) CreateTask(context.Context, *CreateTaskReq) (*CreateTaskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedServicesServiceServer) UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedServicesServiceServer) DeleteTask(context.Context, *DeleteTaskReq) (*DeleteTaskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedServicesServiceServer) GetAllTask(context.Context, *GetAllTaskReq) (*GetAllTaskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTask not implemented")
}
func (UnimplementedServicesServiceServer) GetTaskById(context.Context, *GetTaskByIdReq) (*GetTaskByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskById not implemented")
}
func (UnimplementedServicesServiceServer) mustEmbedUnimplementedServicesServiceServer() {}
func (UnimplementedServicesServiceServer) testEmbeddedByValue()                         {}

// UnsafeServicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicesServiceServer will
// result in compilation errors.
type UnsafeServicesServiceServer interface {
	mustEmbedUnimplementedServicesServiceServer()
}

func RegisterServicesServiceServer(s grpc.ServiceRegistrar, srv ServicesServiceServer) {
	// If the following call pancis, it indicates UnimplementedServicesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicesService_ServiceDesc, srv)
}

func _ServicesService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).DeleteGroup(ctx, req.(*DeleteGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetAllGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetAllGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetAllGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetAllGroup(ctx, req.(*GetAllGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_CreateWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).CreateWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_CreateWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).CreateWorker(ctx, req.(*CreateWorkerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_UpdateWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).UpdateWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_UpdateWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).UpdateWorker(ctx, req.(*UpdateWorkerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_DeleteWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).DeleteWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_DeleteWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).DeleteWorker(ctx, req.(*DeleteWorkerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetAllWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllWorkerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetAllWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetAllWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetAllWorker(ctx, req.(*GetAllWorkerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_CreateAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).CreateAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_CreateAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).CreateAttendance(ctx, req.(*CreateAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_UpdateAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).UpdateAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_UpdateAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).UpdateAttendance(ctx, req.(*UpdateAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_DeleteAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).DeleteAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_DeleteAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).DeleteAttendance(ctx, req.(*DeleteAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetDailyAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetDailyAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetDailyAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetDailyAttendance(ctx, req.(*GetDailyAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetAllAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetAllAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetAllAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetAllAttendance(ctx, req.(*GetAllAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).CreateTask(ctx, req.(*CreateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).UpdateTask(ctx, req.(*UpdateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).DeleteTask(ctx, req.(*DeleteTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetAllTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetAllTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetAllTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetAllTask(ctx, req.(*GetAllTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetTaskById(ctx, req.(*GetTaskByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicesService_ServiceDesc is the grpc.ServiceDesc for ServicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.ServicesService",
	HandlerType: (*ServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _ServicesService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _ServicesService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _ServicesService_DeleteGroup_Handler,
		},
		{
			MethodName: "GetAllGroup",
			Handler:    _ServicesService_GetAllGroup_Handler,
		},
		{
			MethodName: "CreateWorker",
			Handler:    _ServicesService_CreateWorker_Handler,
		},
		{
			MethodName: "UpdateWorker",
			Handler:    _ServicesService_UpdateWorker_Handler,
		},
		{
			MethodName: "DeleteWorker",
			Handler:    _ServicesService_DeleteWorker_Handler,
		},
		{
			MethodName: "GetAllWorker",
			Handler:    _ServicesService_GetAllWorker_Handler,
		},
		{
			MethodName: "CreateAttendance",
			Handler:    _ServicesService_CreateAttendance_Handler,
		},
		{
			MethodName: "UpdateAttendance",
			Handler:    _ServicesService_UpdateAttendance_Handler,
		},
		{
			MethodName: "DeleteAttendance",
			Handler:    _ServicesService_DeleteAttendance_Handler,
		},
		{
			MethodName: "GetDailyAttendance",
			Handler:    _ServicesService_GetDailyAttendance_Handler,
		},
		{
			MethodName: "GetAllAttendance",
			Handler:    _ServicesService_GetAllAttendance_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _ServicesService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _ServicesService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ServicesService_DeleteTask_Handler,
		},
		{
			MethodName: "GetAllTask",
			Handler:    _ServicesService_GetAllTask_Handler,
		},
		{
			MethodName: "GetTaskById",
			Handler:    _ServicesService_GetTaskById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ner-apk-proto/ishlab_chiqarish/services.proto",
}
