// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ner-apk-proto/ishlab_chiqarish/shartnoma.proto

package ishlab_chiqarish

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IshlabChiqarishService_NewContract_FullMethodName                = "/ishlab_chiqarish.IshlabChiqarishService/NewContract"
	IshlabChiqarishService_NewContractUpdate_FullMethodName          = "/ishlab_chiqarish.IshlabChiqarishService/NewContractUpdate"
	IshlabChiqarishService_NewContractDelete_FullMethodName          = "/ishlab_chiqarish.IshlabChiqarishService/NewContractDelete"
	IshlabChiqarishService_NewContractGetName_FullMethodName         = "/ishlab_chiqarish.IshlabChiqarishService/NewContractGetName"
	IshlabChiqarishService_NewContractGetAll_FullMethodName          = "/ishlab_chiqarish.IshlabChiqarishService/NewContractGetAll"
	IshlabChiqarishService_NewInsideTheContract_FullMethodName       = "/ishlab_chiqarish.IshlabChiqarishService/NewInsideTheContract"
	IshlabChiqarishService_NewInsideTheContractUpdate_FullMethodName = "/ishlab_chiqarish.IshlabChiqarishService/NewInsideTheContractUpdate"
	IshlabChiqarishService_NewInsideTheContractDelete_FullMethodName = "/ishlab_chiqarish.IshlabChiqarishService/NewInsideTheContractDelete"
	IshlabChiqarishService_NewInsideTheContractGetAll_FullMethodName = "/ishlab_chiqarish.IshlabChiqarishService/NewInsideTheContractGetAll"
)

// IshlabChiqarishServiceClient is the client API for IshlabChiqarishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IshlabChiqarishServiceClient interface {
	NewContract(ctx context.Context, in *NewContractReq, opts ...grpc.CallOption) (*NewContractRes, error)
	NewContractUpdate(ctx context.Context, in *NewContractUpdateReq, opts ...grpc.CallOption) (*NewContractUpdateRes, error)
	NewContractDelete(ctx context.Context, in *NewContractDeleteReq, opts ...grpc.CallOption) (*NewContractDeleteRes, error)
	NewContractGetName(ctx context.Context, in *NewContractGetNameReq, opts ...grpc.CallOption) (*NewContractGetNameRes, error)
	NewContractGetAll(ctx context.Context, in *NewContractGetAllReq, opts ...grpc.CallOption) (*NewContractGetAllRes, error)
	NewInsideTheContract(ctx context.Context, in *NewInsideTheContractReq, opts ...grpc.CallOption) (*NewInsideTheContractRes, error)
	NewInsideTheContractUpdate(ctx context.Context, in *NewInsideTheContractUpdateReq, opts ...grpc.CallOption) (*NewInsideTheContractUpdateRes, error)
	NewInsideTheContractDelete(ctx context.Context, in *NewInsideTheContractDeleteReq, opts ...grpc.CallOption) (*NewInsideTheContractDeleteRes, error)
	NewInsideTheContractGetAll(ctx context.Context, in *NewInsideTheContractGetAllReq, opts ...grpc.CallOption) (*NewInsideTheContractGetAllRes, error)
}

type ishlabChiqarishServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIshlabChiqarishServiceClient(cc grpc.ClientConnInterface) IshlabChiqarishServiceClient {
	return &ishlabChiqarishServiceClient{cc}
}

func (c *ishlabChiqarishServiceClient) NewContract(ctx context.Context, in *NewContractReq, opts ...grpc.CallOption) (*NewContractRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewContractUpdate(ctx context.Context, in *NewContractUpdateReq, opts ...grpc.CallOption) (*NewContractUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractUpdateRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewContractUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewContractDelete(ctx context.Context, in *NewContractDeleteReq, opts ...grpc.CallOption) (*NewContractDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractDeleteRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewContractDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewContractGetName(ctx context.Context, in *NewContractGetNameReq, opts ...grpc.CallOption) (*NewContractGetNameRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractGetNameRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewContractGetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewContractGetAll(ctx context.Context, in *NewContractGetAllReq, opts ...grpc.CallOption) (*NewContractGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewContractGetAllRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewContractGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewInsideTheContract(ctx context.Context, in *NewInsideTheContractReq, opts ...grpc.CallOption) (*NewInsideTheContractRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewInsideTheContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewInsideTheContractUpdate(ctx context.Context, in *NewInsideTheContractUpdateReq, opts ...grpc.CallOption) (*NewInsideTheContractUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractUpdateRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewInsideTheContractUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewInsideTheContractDelete(ctx context.Context, in *NewInsideTheContractDeleteReq, opts ...grpc.CallOption) (*NewInsideTheContractDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractDeleteRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewInsideTheContractDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ishlabChiqarishServiceClient) NewInsideTheContractGetAll(ctx context.Context, in *NewInsideTheContractGetAllReq, opts ...grpc.CallOption) (*NewInsideTheContractGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewInsideTheContractGetAllRes)
	err := c.cc.Invoke(ctx, IshlabChiqarishService_NewInsideTheContractGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IshlabChiqarishServiceServer is the server API for IshlabChiqarishService service.
// All implementations must embed UnimplementedIshlabChiqarishServiceServer
// for forward compatibility.
type IshlabChiqarishServiceServer interface {
	NewContract(context.Context, *NewContractReq) (*NewContractRes, error)
	NewContractUpdate(context.Context, *NewContractUpdateReq) (*NewContractUpdateRes, error)
	NewContractDelete(context.Context, *NewContractDeleteReq) (*NewContractDeleteRes, error)
	NewContractGetName(context.Context, *NewContractGetNameReq) (*NewContractGetNameRes, error)
	NewContractGetAll(context.Context, *NewContractGetAllReq) (*NewContractGetAllRes, error)
	NewInsideTheContract(context.Context, *NewInsideTheContractReq) (*NewInsideTheContractRes, error)
	NewInsideTheContractUpdate(context.Context, *NewInsideTheContractUpdateReq) (*NewInsideTheContractUpdateRes, error)
	NewInsideTheContractDelete(context.Context, *NewInsideTheContractDeleteReq) (*NewInsideTheContractDeleteRes, error)
	NewInsideTheContractGetAll(context.Context, *NewInsideTheContractGetAllReq) (*NewInsideTheContractGetAllRes, error)
	mustEmbedUnimplementedIshlabChiqarishServiceServer()
}

// UnimplementedIshlabChiqarishServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIshlabChiqarishServiceServer struct{}

func (UnimplementedIshlabChiqarishServiceServer) NewContract(context.Context, *NewContractReq) (*NewContractRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContract not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewContractUpdate(context.Context, *NewContractUpdateReq) (*NewContractUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractUpdate not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewContractDelete(context.Context, *NewContractDeleteReq) (*NewContractDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractDelete not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewContractGetName(context.Context, *NewContractGetNameReq) (*NewContractGetNameRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractGetName not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewContractGetAll(context.Context, *NewContractGetAllReq) (*NewContractGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractGetAll not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewInsideTheContract(context.Context, *NewInsideTheContractReq) (*NewInsideTheContractRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContract not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewInsideTheContractUpdate(context.Context, *NewInsideTheContractUpdateReq) (*NewInsideTheContractUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractUpdate not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewInsideTheContractDelete(context.Context, *NewInsideTheContractDeleteReq) (*NewInsideTheContractDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractDelete not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) NewInsideTheContractGetAll(context.Context, *NewInsideTheContractGetAllReq) (*NewInsideTheContractGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsideTheContractGetAll not implemented")
}
func (UnimplementedIshlabChiqarishServiceServer) mustEmbedUnimplementedIshlabChiqarishServiceServer() {
}
func (UnimplementedIshlabChiqarishServiceServer) testEmbeddedByValue() {}

// UnsafeIshlabChiqarishServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IshlabChiqarishServiceServer will
// result in compilation errors.
type UnsafeIshlabChiqarishServiceServer interface {
	mustEmbedUnimplementedIshlabChiqarishServiceServer()
}

func RegisterIshlabChiqarishServiceServer(s grpc.ServiceRegistrar, srv IshlabChiqarishServiceServer) {
	// If the following call pancis, it indicates UnimplementedIshlabChiqarishServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IshlabChiqarishService_ServiceDesc, srv)
}

func _IshlabChiqarishService_NewContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewContract(ctx, req.(*NewContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewContractUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewContractUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewContractUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewContractUpdate(ctx, req.(*NewContractUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewContractDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewContractDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewContractDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewContractDelete(ctx, req.(*NewContractDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewContractGetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractGetNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewContractGetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewContractGetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewContractGetName(ctx, req.(*NewContractGetNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewContractGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContractGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewContractGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewContractGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewContractGetAll(ctx, req.(*NewContractGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewInsideTheContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewInsideTheContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContract(ctx, req.(*NewInsideTheContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewInsideTheContractUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewInsideTheContractUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractUpdate(ctx, req.(*NewInsideTheContractUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewInsideTheContractDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewInsideTheContractDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractDelete(ctx, req.(*NewInsideTheContractDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IshlabChiqarishService_NewInsideTheContractGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInsideTheContractGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IshlabChiqarishService_NewInsideTheContractGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IshlabChiqarishServiceServer).NewInsideTheContractGetAll(ctx, req.(*NewInsideTheContractGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IshlabChiqarishService_ServiceDesc is the grpc.ServiceDesc for IshlabChiqarishService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IshlabChiqarishService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ishlab_chiqarish.IshlabChiqarishService",
	HandlerType: (*IshlabChiqarishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewContract",
			Handler:    _IshlabChiqarishService_NewContract_Handler,
		},
		{
			MethodName: "NewContractUpdate",
			Handler:    _IshlabChiqarishService_NewContractUpdate_Handler,
		},
		{
			MethodName: "NewContractDelete",
			Handler:    _IshlabChiqarishService_NewContractDelete_Handler,
		},
		{
			MethodName: "NewContractGetName",
			Handler:    _IshlabChiqarishService_NewContractGetName_Handler,
		},
		{
			MethodName: "NewContractGetAll",
			Handler:    _IshlabChiqarishService_NewContractGetAll_Handler,
		},
		{
			MethodName: "NewInsideTheContract",
			Handler:    _IshlabChiqarishService_NewInsideTheContract_Handler,
		},
		{
			MethodName: "NewInsideTheContractUpdate",
			Handler:    _IshlabChiqarishService_NewInsideTheContractUpdate_Handler,
		},
		{
			MethodName: "NewInsideTheContractDelete",
			Handler:    _IshlabChiqarishService_NewInsideTheContractDelete_Handler,
		},
		{
			MethodName: "NewInsideTheContractGetAll",
			Handler:    _IshlabChiqarishService_NewInsideTheContractGetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ner-apk-proto/ishlab_chiqarish/shartnoma.proto",
}
